// client-solid/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Route, Router } from "@solidjs/router";

import "./index.css";
import App from "./App";

const root = document.getElementById("root");

// render(() => <App />, root!);

const About = () => {
    return (
        <div class="flex text-2xl justify-center">
            <p>About page</p>
        </div>
    )
}

render(
  () => (
    <Router>
      <Route path="/" component={App} />
      <Route path="/about" component={About}/>
    </Router>
  ),
  root!
);

// client/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

import { createBrowserRouter, RouterProvider } from "react-router-dom";

const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
  },
  {
    path: "/about",
    element: (
      <div>
        <p>About page</p>
      </div>
    ),
  },
]);

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
